name: STOSC
description: St. Thomas Orthodox Syrian Cathedral
paginate: 5
# baseurl: '/stosc'
encoding: utf-8
#Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
exclude: [vendor]